Repository FederatedAI/eggroll, pull requests merged in 2019-08, with the labels that each got.

#20 processor support multiple storage engines#19 #21
  api/cluster/clustercomm.py
  api/cluster/eggroll.py
  api/standalone/clustercomm.py
  api/standalone/eggroll.py
  computing/processor-old.py
  computing/processor.py
  computing/storage_adapters.py
Labels: enhancement

#23 update deploy files
  cluster-deploy/example-dir-tree/egg/conf/egg.properties
  cluster-deploy/scripts/auto-module-deploy.sh
  cluster-deploy/scripts/auto-single-deploy.sh
Labels: documentation

#24 Feature 1.0 nm enhancement
  api/cluster/eggroll.py
  api/eggroll.py
  api/standalone/eggroll.py
  cluster-deploy/Eggroll Deployment Guide.md
  cluster-deploy/doc/configuration.md
  cluster-deploy/example-dir-tree/clustercomm/conf/applicationContext-clustercomm.xml
  cluster-deploy/example-dir-tree/clustercomm/conf/clustercomm.properties
  cluster-deploy/example-dir-tree/clustercomm/conf/log4j2.properties
  cluster-deploy/example-dir-tree/egg/conf/applicationContext-egg.xml
  cluster-deploy/example-dir-tree/egg/conf/egg.properties
  cluster-deploy/example-dir-tree/egg/conf/log4j2.properties
  cluster-deploy/example-dir-tree/meta-service/conf/applicationContext-meta-service.xml
  cluster-deploy/example-dir-tree/meta-service/conf/log4j2.properties
  cluster-deploy/example-dir-tree/meta-service/conf/meta-service.properties
  cluster-deploy/example-dir-tree/proxy/conf/applicationContext-proxy.xml
  cluster-deploy/example-dir-tree/proxy/conf/log4j2.properties
  cluster-deploy/example-dir-tree/proxy/conf/proxy.properties
  cluster-deploy/example-dir-tree/proxy/conf/route_table.json
  cluster-deploy/example-dir-tree/roll/conf/applicationContext-roll.xml
  cluster-deploy/example-dir-tree/roll/conf/log4j2.properties
  cluster-deploy/example-dir-tree/roll/conf/roll.properties
  cluster-deploy/example-dir-tree/services.sh
  cluster-deploy/scripts/auto-module-deploy.sh
  cluster-deploy/scripts/auto-packaging.sh
  cluster-deploy/scripts/auto-single-deploy.sh
  cluster-deploy/scripts/configurations.sh
  cluster-deploy/scripts/modify_json.py
  cluster-deploy/scripts/single-configurations.sh
  doc/api.md
  framework/egg/src/main/java/com/webank/ai/eggroll/framework/egg/computing/impl/ProcessorEngineOperator.java
  framework/roll/src/main/java/com/webank/ai/eggroll/framework/roll/api/grpc/server/RollProcessServiceImpl.java
  pom.xml
  storage/storage-service-cxx/Makefile
  storage/storage-service-cxx/src/RocksDBStore.cc
Labels: bug, enhancement

#26 Fixed issue #25
  computing/storage_adapters.py
Labels: bug

#31 Add third_party source
  cluster-deploy/Eggroll Deployment Guide.md
Labels: documentation

#33 add is_stopped interface to enhance gc reliability #32
  api/cluster/eggroll.py
  api/standalone/eggroll.py
  computing/storage_adapters.py
Labels: bug

#36 Fix stop api of standalone mode and __create_binary_process of cluster mode
  api/cluster/eggroll.py
  api/standalone/eggroll.py
Labels: bug
