Repository FederatedAI/eggroll, pull requests merged in 2019-10, with the labels that each got.

#60 Release 1.1 build3
  PULL_REQUEST_TEMPLATE.md
  README.md
  doc/api.md
  logo.png
Labels: v1.x

#62 Merge back for v1.1.1
  PULL_REQUEST_TEMPLATE.md
  README.md
  doc/api.md
  logo.png
Labels: v1.x

#64 fix issue #63 #58
  api/cluster/eggroll.py
  api/standalone/eggroll.py
Labels: bug, v1.x

#66 Changes:
  api/utils/eggroll_serdes.py
Labels: security

#70 Feature 1.1.1 fate v1.1 compatibility enhancement
  api/cluster/eggroll.py
  api/core.py
  api/standalone/eggroll.py
  api/utils/eggroll_serdes.py
  api/utils/iter_utils.py
  core/src/main/java/com/webank/ai/eggroll/core/constant/RuntimeConstants.java
  core/src/main/java/com/webank/ai/eggroll/core/factory/CallMetaModelFactory.java
  core/src/main/java/com/webank/ai/eggroll/core/factory/GrpcChannelFactory.java
  core/src/main/java/com/webank/ai/eggroll/core/utils/TypeConversionUtils.java
  core/src/main/java/com/webank/ai/fate/eggroll/meta/service/dao/generated/model/Dtable.java
  core/src/main/java/com/webank/ai/fate/eggroll/meta/service/dao/generated/model/Fragment.java
  framework/egg/src/main/java/com/webank/ai/eggroll/framework/egg/computing/impl/ProcessorEngineOperator.java
  framework/egg/src/test/java/com/webank/ai/eggroll/framework/egg/TestSession.java
  framework/meta-service/src/main/java/com/webank/ai/eggroll/framework/MetaService.java
  framework/meta-service/src/main/java/com/webank/ai/eggroll/framework/meta/service/api/grpc/server/StorageMetaServiceImpl.java
  framework/meta-service/src/main/java/com/webank/ai/eggroll/framework/meta/service/service/impl/DefaultStrategyGrpcCrudService.java
  framework/roll/src/main/java/com/webank/ai/eggroll/framework/roll/api/grpc/server/RollKvServiceImpl.java
Labels: bug, enhancement, v1.x

#79 Feature 1.1.1 fate v1.1 compatibility enhancement
  api/core.py
Labels: bug

#80 Feature 1.1.1 fate v1.1 compatibility enhancement bugfix for intersect problem
  api/core.py
Labels: bug

#86 Feature 1.1.1 deploy doc
  README.md
  cluster-deploy/Eggroll Deployment Guide.md
  cluster-deploy/scripts/auto-module-deploy.sh
  cluster-deploy/scripts/auto-single-deploy.sh
  cluster-deploy/scripts/configurations.sh
  cluster-deploy/scripts/single-configurations.sh
  doc/api.md
Labels: documentation, v1.x

#87 Doc change for v1.x
  .sat.toml
  README.md
  cluster-deploy/Eggroll Deployment Guide.md
  cluster-deploy/scripts/auto-module-deploy.sh
  cluster-deploy/scripts/auto-single-deploy.sh
  cluster-deploy/scripts/configurations.sh
  cluster-deploy/scripts/single-configurations.sh
  doc/api.md
Labels: documentation, v1.x

#96 Release of v1.1.1
  .sat.toml
  README.md
  api/cluster/eggroll.py
  api/core.py
  api/standalone/eggroll.py
  api/utils/eggroll_serdes.py
  api/utils/iter_utils.py
  cluster-deploy/Eggroll Deployment Guide.md
  cluster-deploy/scripts/auto-module-deploy.sh
  cluster-deploy/scripts/auto-single-deploy.sh
  cluster-deploy/scripts/configurations.sh
  cluster-deploy/scripts/single-configurations.sh
  core/src/main/java/com/webank/ai/eggroll/core/constant/RuntimeConstants.java
  core/src/main/java/com/webank/ai/eggroll/core/factory/CallMetaModelFactory.java
  core/src/main/java/com/webank/ai/eggroll/core/factory/GrpcChannelFactory.java
  core/src/main/java/com/webank/ai/eggroll/core/utils/TypeConversionUtils.java
  core/src/main/java/com/webank/ai/eggroll/meta/service/dao/generated/model/Dtable.java
  core/src/main/java/com/webank/ai/eggroll/meta/service/dao/generated/model/Fragment.java
  core/src/main/java/com/webank/ai/eggroll/meta/service/dao/generated/model/Node.java
  doc/api.md
  framework/egg/src/main/java/com/webank/ai/eggroll/framework/egg/computing/impl/ProcessorEngineOperator.java
  framework/egg/src/main/java/com/webank/ai/eggroll/framework/egg/manager/EggSessionManager.java
  framework/egg/src/test/java/com/webank/ai/eggroll/framework/egg/TestSession.java
  framework/meta-service/src/main/java/com/webank/ai/eggroll/framework/MetaService.java
  framework/meta-service/src/main/java/com/webank/ai/eggroll/framework/meta/service/api/grpc/server/StorageMetaServiceImpl.java
  framework/meta-service/src/main/java/com/webank/ai/eggroll/framework/meta/service/service/impl/DefaultStrategyGrpcCrudService.java
  framework/roll/src/main/java/com/webank/ai/eggroll/framework/roll/api/grpc/server/RollKvServiceImpl.java
Labels: v1.x
