Repository FederatedAI/eggroll, pull requests merged in 2019-12, with the labels that each got.

#126 fix load bug
  roll_objects/roll_pair/python/eggroll/roll_pair/roll_pair.py
  roll_objects/roll_pair/python/test/test_roll_pair.py
Labels: bug, v2.x

#153 Update issue templates
  .github/ISSUE_TEMPLATE/--issue-report.md
Labels: documentation

#161 Feature 2.0 framework
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/clustermanager/session/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/TransferService.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/component/RollPairServicer.scala
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/shuffler.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#162 remote api pass
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/scala/putBatch.scala
  python/eggroll/core/io/format.py
  python/eggroll/core/io/rollsite_adapter.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: v2.x

#163 commit destroy, delete and save_as
  python/eggroll/core/io/kv_adapter.py
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
Labels: enhancement, v2.x

#166 Update issue templates
  .github/ISSUE_TEMPLATE/--issue-report.md
Labels: documentation

#168 Feature 2.0 rollpair
  python/arch/api/test/test_fate_api.py
  python/eggroll/core/io/kv_adapter.py
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
Labels: enhancement, v2.x

#169 refactor roll pair
  python/eggroll/roll_pair/__init__.py
  python/eggroll/roll_pair/utils/pair_utils.py
Labels: enhancement, v2.x

#170 Feature 2.0 framework
  bin/eggroll_boot_standalone.sh
  jvm/core/main/resources/create-eggroll-meta-tables.h2.sql
  jvm/core/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/JdbcTemplate.scala
  jvm/core/test/scala/com/webank/eggroll/core/resourcemanager/ResourceDaoTests.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Main.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/component/RollPairServicer.scala
  proto/core/transfer.proto
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/proto/transfer_pb2.py
  python/eggroll/core/proto/transfer_pb2_grpc.py
  python/eggroll/core/session.py
  python/eggroll/core/test/test_transfer.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_paillier_tensor/roll_paillier_tensor.py
  python/eggroll/roll_paillier_tensor/test/test_lr.py
  python/eggroll/roll_paillier_tensor/test/test_roll_paillier_tensor.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_io.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#172 Working test set
  python/eggroll/roll_pair/test/test_standalone.py
Labels: v2.x

#183 Feature 2.0 core
  bin/eggroll_boot.sh
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/java/com/webank/eggroll/core/client/NodeManagerClient.java
  jvm/core/main/resources/create-eggroll-meta-tables.sql
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/client/ClusterManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/clustermanager/ClusterManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/clustermanager/session/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandRouter.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/CommandConstants.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/EggManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/HeartBeat.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/NodeManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/RollManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/core/main/scala/com/webank/eggroll/core/session/ErConf.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/JdbcTemplate.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/MiscellaneousUtils.scala
  jvm/core/test/scala/com/webank/eggroll/core/nodemanager/TestNodeManager.scala
  jvm/core/test/scala/com/webank/eggroll/core/resourcemanager/TestAssets.scala
  jvm/core/test/scala/com/webank/eggroll/core/resourcemanager/TestContainer.scala
  jvm/core/test/scala/com/webank/eggroll/core/resourcemanager/TestResourceDao.scala
  jvm/core/test/scala/com/webank/eggroll/core/resourcemanager/TestSessionManager.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Main.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/StandaloneManager.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/client/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/component/RollPairMaster.scala
  jvm/roll_pair/test/scala/com/webank/eggroll/rollpair/io/TestRollPair.scala
  proto/core/meta.proto
  python/eggroll/core/client.py
  python/eggroll/core/command/commands.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/constants.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/proto/meta_pb2.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
Labels: v2.x

#185 Feature 2.0 core
  bin/eggroll_boot_standalone.sh
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/client/ClusterManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/core/test/scala/com/webank/eggroll/core/schedule/TestProcessOperator.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  python/eggroll/core/client.py
  python/eggroll/core/command/commands.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/constants.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/session.py
  python/eggroll/core/test/test_pair_store.py
  python/eggroll/core/test/test_session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_roll_pair_context.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_site/test/test_push.py
Labels: v2.x

#188 Feature 2.0 core
  bin/eggroll_boot_standalone.sh
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  conf/standalone-manager-log4j2.properties
  jvm/core/main/resources/cluster-manager.properties
  jvm/core/main/scala/com/webank/eggroll/core/Bootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/clustermanager/ClusterManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/clustermanager/constant/RdbConstants.scala
  jvm/core/main/scala/com/webank/eggroll/core/clustermanager/session/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/EggManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/HeartBeat.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/NodeManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/nodemanager/RollManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Rdb.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/CrudOperatorTemplate.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/ServerNodeCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/deploy/JvmProcessorOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/deploy/PythonProcessorOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/JdbcTemplate.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/Utils.scala
  jvm/core/test/scala/com/webank/eggroll/core/clustermanager/TestClusterManagerClient.scala
  jvm/core/test/scala/com/webank/eggroll/core/clustermanager/TestServerNodeCrudOperator.scala
  jvm/core/test/scala/com/webank/eggroll/core/clustermanager/TestStoreCrudOperator.scala
  jvm/core/test/scala/com/webank/eggroll/core/nodemanager/TestNodeManager.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Main.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/StandaloneManager.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/component/RollPairContext.scala
  python/eggroll/core/conf_keys.py
  python/eggroll/core/constants.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#191 Feature 2.0 rollpair
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/Pipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/BasePipe.java
  python/arch/api/test/test_fate_api.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/roll_site.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/test_pull.py
  python/eggroll/roll_site/test/test_push.py
  python/eggroll/roll_site/test/test_rollsite_adpter.py
  python/eggroll/roll_site/utils/eggroll_serdes.py
Labels: bug, v2.x

#192 Feature 2.0 core
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  data/meta_h2/eggroll_meta.h2.mv.db
  jvm/core/main/java/com/webank/eggroll/core/grpc/client/GrpcClientContext.java
  jvm/core/main/java/com/webank/eggroll/core/grpc/client/GrpcClientTemplate.java
  jvm/core/main/java/com/webank/eggroll/core/grpc/processor/BaseClientCallStreamProcessor.java
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandRouter.scala
  jvm/core/main/scala/com/webank/eggroll/core/io/adapter/BlockDeviceAdapter.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/deploy/ExecutableProcessorOperator.scala
  jvm/core/test/resources/meta.h2.mv.db
  jvm/core/test/resources/meta.h2.trace.db
  jvm/core/test/scala/com/webank/eggroll/core/nodemanager/TestOperator.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/format/FrameDB.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/EggPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Main.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairDriver.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMaster.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Shuffler.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/client/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/component/RollPairMaster.scala
  jvm/roll_pair/test/scala/com/webank/eggroll/rollpair/io/TestIo.scala
  jvm/roll_pair/test/scala/com/webank/eggroll/rollpair/io/TestRollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/ConfFileBasedFdnRouter.java
  python/eggroll/core/client.py
  python/eggroll/core/command/command_client.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
Labels: v2.x

#195 Feature-2.0-core
  python/eggroll/core/base_model.py
  python/eggroll/core/client.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/command/command_service.py
  python/eggroll/core/command/commands.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/constants.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/datastructure/concurrent.py
  python/eggroll/core/grpc/factory.py
  python/eggroll/core/serdes.py
  python/eggroll/core/serdes/eggroll_serdes.py
  python/eggroll/core/transfer_model.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/utils/file_utils.py
  python/eggroll/utils/log_utils.py
Labels: v2.x

#197 Feature 2.0 rollpair
  python/eggroll/core/constants.py
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
Labels: bug, v2.x

#198 Feature 2.0 core
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/session/ErConf.scala
  python/eggroll/core/client.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/format.py
  python/eggroll/core/session.py
  python/eggroll/core/test/test_transfer.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_pair/utils/pair_utils.py
Labels: v2.x

#201 Feature 2.0 rollpair
  data/meta_h2/eggroll_meta.h2.mv.db
  jvm/core/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  python/eggroll/core/constants.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
Labels: enhancement, v2.x

#202 Feature 2.0 core
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#203 1. fixed data dir issues.
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
Labels: v2.x

#204 Feature 2.0 rollpair
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_standalone.py
Labels: enhancement, v2.x

#205 Feature 2.0 core
  .gitattributes
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/client/ClusterManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/test/scala/com/webank/eggroll/rollpair/io/TestIo.scala
  python/eggroll/core/session.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_standalone.py
Labels: v2.x

#215 Feature 2.0 rollpair
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: enhancement, v2.x

#216 rename get_serdes to get_store_serdes
  python/eggroll/roll_pair/roll_pair.py
Labels: bug, v2.x

#217 Feature 2.0 core
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  python/eggroll/core/command/command_router.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/io/kv_adapter.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/utils.py
  python/eggroll/roll_paillier_tensor/roll_paillier_tensor.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_interface.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/utils/log_utils.py
Labels: v2.x

#218 cluster mode test case pass
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/test_rollsite.py
Labels: v2.x

#221 fix session stop problem
  api/cluster/eggroll.py
Labels: bug, v1.x
