Repository FederatedAI/eggroll, pull requests merged in 2019-11, with the labels that each got.

#99 Feature 1.2 performance enhancement
  .sat.toml
  README.md
  cluster-deploy/Eggroll Deployment Guide.md
  cluster-deploy/scripts/auto-module-deploy.sh
  cluster-deploy/scripts/auto-single-deploy.sh
  cluster-deploy/scripts/configurations.sh
  cluster-deploy/scripts/single-configurations.sh
  computing/processor.py
  core/pom.xml
  doc/api.md
  framework/egg/src/main/java/com/webank/ai/eggroll/framework/egg/computing/impl/ProcessorEngineOperator.java
  framework/egg/src/main/java/com/webank/ai/eggroll/framework/egg/manager/EggSessionManager.java
Labels: enhancement, v1.x

#100 fix uuid problem
  api/cluster/eggroll.py
Labels: bug, v1.x

#104 fix cleanup task
  api/core.py
Labels: bug, v1.x

#107 fix reduce problem
  api/core.py
  computing/processor.py
Labels: bug, v1.x

#110 fix print
  api/cluster/eggroll.py
Labels: bug, v1.x

#112 Feature 1.3 fix reduce duplicated table
  api/cluster/eggroll.py
  api/standalone/eggroll.py
Labels: bug, v1.x

#111 fix standalone print
  api/standalone/eggroll.py
Labels: bug, v1.x

#115 Release 1.1.2 build3
  api/cluster/eggroll.py
  api/standalone/eggroll.py
  computing/processor.py
Labels: bug, v1.x

#116 Feature 2.0 roll pair storage computing
  core/jvm/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  core/python/eggroll/core/command/command_client.py
  core/python/eggroll/core/io/kv_adapter.py
  core/python/eggroll/core/meta_model.py
  core/python/eggroll/core/serdes/eggroll_serdes.py
  core/python/eggroll/core/utils.py
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/component/RollPairService.scala
  roll_objects/roll_pair/jvm/test/scala/com/webank/eggroll/rollpair/io/TestRollPair.scala
  roll_objects/roll_pair/python/eggroll/roll_pair/egg_pair.py
  roll_objects/roll_pair/python/eggroll/roll_pair/roll_pair.py
  roll_objects/roll_pair/python/test/test_roll_pair.py
  roll_objects/roll_pair/python/test/test_storage.py
Labels: enhancement, v2.x

#118 Feature 2.0 framework
  core/jvm/main/java/com/webank/eggroll/core/client/ClusterManagerClient.java
  core/jvm/main/java/com/webank/eggroll/core/client/NodeManagerClient.java
  core/jvm/main/scala/com/webank/eggroll/core/client/MetadataClient.scala
  core/jvm/main/scala/com/webank/eggroll/core/command/CommandFramework.scala
  core/jvm/main/scala/com/webank/eggroll/core/command/CommandRouter.scala
  core/jvm/main/scala/com/webank/eggroll/core/command/CommandService.scala
  core/jvm/main/scala/com/webank/eggroll/core/constant/CommandConstants.scala
  core/jvm/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  core/jvm/main/scala/com/webank/eggroll/core/constant/StringConstants.scala
  core/jvm/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  core/jvm/main/scala/com/webank/eggroll/core/datastructure/Traits.scala
  core/jvm/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  core/jvm/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  core/jvm/main/scala/com/webank/eggroll/core/schedule/deploy/JvmProcessorOperator.scala
  core/jvm/main/scala/com/webank/eggroll/core/schedule/deploy/PythonProcessorOperator.scala
  core/jvm/main/scala/com/webank/eggroll/core/session/ErConf.scala
  core/jvm/main/scala/com/webank/eggroll/core/session/GrpcServerConf.scala
  core/jvm/test/scala/com/webank/eggroll/core/schedule/TestProcessOperator.scala
  core/proto/meta.proto
  core/python/eggroll/core/client.py
  core/python/eggroll/core/command/command_client.py
  core/python/eggroll/core/command/commands.py
  core/python/eggroll/core/constants.py
  core/python/eggroll/core/meta_model.py
  core/python/eggroll/core/proto/meta_pb2.py
  core/python/eggroll/core/session.py
  core/python/eggroll/core/transfer/transfer_service.py
  core/python/eggroll/core/utils.py
  framework/cluster_manager/jvm/main/resources/create-eggroll-meta-tables.sql
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/Main.scala
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/constant/ClusterManagerCommands.scala
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/constant/SessionConstants.scala
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/metadata/StoreCrudOperator.scala
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/session/SessionDeployer.scala
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/session/SessionManager.scala
  framework/cluster_manager/jvm/pom.xml
  framework/cluster_manager/jvm/test/scala/com/webank/eggroll/clustermanager/metadata/TestClusterManagerClientMetaService.scala
  framework/cluster_manager/python/eggroll/cluster_manager/cluster_manager_client.py
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/Main.scala
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/component/HeartBeat.scala
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/component/NodeManagerServicer.scala
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/component/ProcessorManager.scala
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/component/ServicerManager.scala
  framework/node_manager/jvm/pom.xml
  framework/node_manager/jvm/test/resources/log4j2-test.properties
  framework/node_manager/jvm/test/scala/TestNodeManager.scala
  framework/node_manager/jvm/test/scala/TestOperator.scala
  pom.xml
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/Main.scala
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/client/RollPair.scala
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/component/RollPairContext.scala
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/component/RollPairServicer.scala
  roll_objects/roll_pair/jvm/pom.xml
  roll_objects/roll_pair/jvm/test/scala/com/webank/eggroll/rollpair/io/TestRollPair.scala
  roll_objects/roll_pair/python/eggroll/roll_pair/egg_pair.py
  roll_objects/roll_pair/python/test/test_roll_pair.py
Labels: v2.x

#121 1. Working version of create session and its servicer / processors.
  core/jvm/main/scala/com/webank/eggroll/core/schedule/deploy/JvmProcessorOperator.scala
  core/jvm/main/scala/com/webank/eggroll/core/util/MiscellaneousUtils.scala
  core/python/eggroll/core/client.py
  core/python/eggroll/core/conf_keys.py
  core/python/eggroll/core/constants.py
  core/python/eggroll/core/meta_model.py
  core/python/eggroll/core/serdes/eggroll_serdes.py
  core/python/eggroll/core/session.py
  core/python/test/test_session.py
  framework/cluster_manager/jvm/main/scala/com/webank/eggroll/clustermanager/Main.scala
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/Main.scala
  framework/node_manager/jvm/main/scala/com/webank/eggroll/nodemanager/component/ServicerManager.scala
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/Main.scala
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/client/RollPair.scala
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/component/Shuffler.scala
  roll_objects/roll_pair/jvm/test/scala/com/webank/eggroll/rollpair/io/TestIo.scala
  roll_objects/roll_pair/python/eggroll/roll_pair/egg_pair.py
  roll_objects/roll_pair/python/eggroll/roll_pair/roll_pair.py
Labels: v2.x

#123 1. add destroy and pair_store
  core/python/eggroll/core/io/kv_adapter.py
  core/python/eggroll/core/utils.py
  roll_objects/roll_pair/jvm/main/scala/com/webank/eggroll/rollpair/Main.scala
  roll_objects/roll_pair/python/eggroll/roll_pair/egg_pair.py
  roll_objects/roll_pair/python/eggroll/roll_pair/roll_pair.py
  roll_objects/roll_pair/python/test/test_roll_pair.py
Labels: enhancement, v2.x
