Repository FederatedAI/eggroll, pull requests merged in 2020-05, with the labels that each got.

#360 Feature 2.0 core
  bin/eggroll_boot.sh
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  python/eggroll/roll_pair/roll_pair.py
Labels: bug, v2.x

#361 Feature 2.0 core
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, v2.x

#362 Feature 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/pair_utils.py
Labels: enhancement, v2.x

#363 Adds lock in broker active count.
  python/eggroll/core/datastructure/broker.py
Labels: bug, v2.x

#364 1. Updates log level and contents.
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: enhancement, v2.x

#365 Merges 2.0.1 build 10 to 2.1
  BUILD_INFO
  bin/eggroll_boot.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/GrpcUtils.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  python/arch/api/__init__.py
  python/arch/api/federation.py
  python/arch/api/session.py
  python/arch/api/table/__init__.py
  python/arch/api/table/eggroll2/__init__.py
  python/arch/api/table/eggroll2/session_impl.py
  python/arch/api/table/eggroll2/table_impl.py
  python/arch/api/table/eggroll_util.py
  python/arch/api/table/session.py
  python/arch/api/table/table.py
  python/arch/api/test/test_fate_api.py
  python/arch/api/transfer/__init__.py
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/core/client.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/grpc/factory.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_interface.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_pair/utils/pair_utils.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/fate_flow/driver/task_executor.py
  python/fate_flow/driver/task_scheduler.py
  python/fate_flow/entity/constant_config.py
  python/fate_flow/fate_flow_server.py
  python/fate_flow/utils/grpc_utils.py
  python/federatedml/secureprotol/fate_paillier.py
  python/federatedml/secureprotol/fixedpoint.py
  python/federatedml/secureprotol/gmpy_math.py
Labels: v2.x

#366 db operation serialized now
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/ServerNodeCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  python/eggroll/roll_site/roll_site.py
Labels: bug, v2.x

#367 Feature 2.1 rollpair
  jvm/core/main/scala/com/webank/eggroll/core/error/ErSessionException.scala
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: enhancement, v2.x

#372 Feature 2.1 database operator
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  python/eggroll/core/meta_model.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
Labels: v2.x

#374 Feature 2.1 core
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/ServerNodeCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/Logging.scala
  python/eggroll/core/meta_model.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: bug, enhancement, v2.x

#375 Feature 2.1 core
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#377 Feature 2.1 rollpair
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/format.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/test/test_pair_store.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#379 Feature 2.1 core
  bin/connect_to_h2.sh
  bin/eggroll_boot.sh
  bin/eggroll_boot_standalone.sh
  data/meta_h2/eggroll_meta.h2.mv.db
  python/eggroll/core/pair_store/roll_site_adapter.py
Labels: v2.x

#381 Feature 2.1 rollframe
  bin/eggroll.sh
  bin/roll_frame/egg_frame_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/util/Logging.scala
  jvm/pom.xml
  jvm/roll_frame/pom.xml
  jvm/roll_frame/src/main/resources/META-INF/MANIFEST.MF
  jvm/roll_frame/src/main/scala/com/webank/eggroll/format/BlockDeviceAdapter.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/format/FrameFormat.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/format/FrameStore.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/rollframe/EggFrame.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/rollframe/EggFrameBootstrap.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/rollframe/RollFrame.scala
  jvm/roll_frame/src/main/scala/com/webank/eggroll/rollframe/TransferService.scala
  jvm/roll_frame/src/test/scala/com/webank/eggroll/rollframe/FrameFormatTests.scala
  jvm/roll_frame/src/test/scala/com/webank/eggroll/rollframe/FrameTransferTests.scala
  jvm/roll_frame/src/test/scala/com/webank/eggroll/rollframe/RollFrameTests.scala
  jvm/roll_frame/src/test/scala/com/webank/eggroll/rollframe/SparkAppTest.scala
  jvm/roll_frame/src/test/scala/com/webank/eggroll/rollframe/TestAssets.scala
  jvm/roll_site/pom.xml
Labels: v2.x

#382 Feature 2.1 rollsite
  python/eggroll/core/session.py
  python/eggroll/roll_site/roll_site.py
Labels: enhancement, v2.x

#383 Feature 2.1 core
  bin/roll_frame/egg_frame_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/util/Logging.scala
  python/eggroll/core/conf_keys.py
  python/eggroll/roll_pair/roll_pair.py
Labels: v2.x

#385 Feature 2.1 core
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.py
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/pom.xml
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: enhancement, v2.x

#387 Feature 2.1 rollpair
  python/eggroll/core/constants.py
  python/eggroll/roll_pair/roll_pair.py
Labels: bug

#388 Feature 2.1 rollsite
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
Labels: v2.x

#390 rocksdb / default store type optimisations
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/core/pair_store/rocksdb.py
Labels: v2.x

#391 1. Removes deprecated MANIFEST.MF.
  jvm/core/main/java/META-INF/MANIFEST.MF
Labels: bug

#393 Feature 2.1 rollframe
  jvm/pom.xml
  jvm/roll_frame/src/main/scala/com/webank/eggroll/rollframe/RollFrame.scala
Labels: v2.x
