Repository FederatedAI/eggroll, pull requests merged in 2020-12, with the labels that each got.

#484 Make long retry configurable.
  python/eggroll/core/conf_keys.py
  python/eggroll/roll_site/roll_site.py
Labels: module=rollsite, reason=enhancement, version=v2.x

#487 Feature 2.2.1 retry
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/EggSiteBootstrap.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/Router.scala
Labels: module=rollsite, reason=enhancement, version=v2.x

#486 change version info from 2.2.0 to 2.2.1
  BUILD_INFO
  jvm/pom.xml
  python/eggroll/__init__.py
Labels: version=v2.x

#488 1. Updates start script.
  bin/eggroll.sh
Labels: module=deployment, reason=enhancement, version=v2.x

#490 1. Adds direct memory metric logging.
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/Utils.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/EggSiteBootstrap.scala
Labels: reason=enhancement, version=v2.x

#492 fix import error
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/roll_pair/egg_pair.py
Labels: module=rollpair, reason=bug, version=v2.x

#495 update numba and llvmlite version
  requirements.txt
Labels: module=dependencies

#493 Release 2.3.0 build 3 -> main
  BUILD_INFO
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Rdb.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/JdbcTemplate.scala
  jvm/pom.xml
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/Push.scala
  python/eggroll/__init__.py
  python/eggroll/roll_pair/task/storage.py
  python/eggroll/roll_site/roll_site.py
Labels: module=core, module=rollsite, version=v2.x
