Repository FederatedAI/eggroll, pull requests merged in 2020-04, with the labels that each got.

#308 Feature 2.0 add version file
  README.md
Labels: documentation, v2.x

#319 Feature 2.0 core
  BUILD_INFO
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/pom.xml
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMaster.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  jvm/roll_site/pom.xml
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  requirements.txt
Labels: bug, dependencies, v2.x

#320 Feature 2.0 core
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/mapper/ServerNodeMapper.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/mapper/ServerNodeMapper.xml
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/mapper/StoreLocatorMapper.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/mapper/StoreLocatorMapper.xml
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/mapper/StorePartitionMapper.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/mapper/StorePartitionMapper.xml
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/model/ServerNode.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/model/ServerNodeExample.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/model/StoreLocator.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/model/StoreLocatorExample.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/model/StorePartition.java
  jvm/core/main/java/com/webank/eggroll/core/clustermanager/dao/generated/model/StorePartitionExample.java
  jvm/core/main/java/com/webank/eggroll/core/factory/GrpcChannelFactory.java
  jvm/core/main/java/com/webank/eggroll/core/factory/GrpcServerFactory.java
  jvm/core/main/java/com/webank/eggroll/core/factory/GrpcStubFactory.java
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Rdb.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/CrudOperatorTemplate.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/ServerNodeCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/GrpcUtils.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/TransferService.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/ThreadPoolUtils.scala
  jvm/core/pom.xml
  jvm/core/test/scala/com/webank/eggroll/core/command/TestCommandService.scala
  jvm/core/test/scala/com/webank/eggroll/core/util/TestReflectionUtils.java
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/CascadedCaller.java
  jvm/roll_site/pom.xml
  python/eggroll/roll_pair/roll_pair.py
Labels: refactoring, v2.x

#321 Optimized roll site to make it work at ~ 50% error rate.
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/DataTransferPipedClient.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/PushClientResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/BasePipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/CascadedCaller.java
  jvm/roll_site/pom.xml
  python/eggroll/core/pair_store/roll_site_adapter.py
Labels: enhancement, security, v2.x

#324 Roll Site and standalone optimizations
  bin/eggroll_boot_standalone.sh
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  python/eggroll/core/client.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
Labels: bug, enhancement, v2.x

#328 Pid and startup log improvements.
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  python/eggroll/roll_pair/egg_pair.py
Labels: bug, enhancement, v2.x

#329 Feature 2.1 database operator
  bin/eggroll.sh
  deploy/Eggroll Deployment Guide.md
  deploy/Eggroll部署文档说明.md
  deploy/deploy.sh
  deploy/init.sh
  jvm/core/main/resources/create-eggroll-meta-tables.h2.sql
  jvm/core/main/resources/create-eggroll-meta-tables.sql
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/DbModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
Labels: enhancement, v2.x

#331 Feature 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/error/DistributedRuntimeException.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Shuffler.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
Labels: enhancement, v2.x

#332 Feature 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  jvm/core/main/scala/com/webank/eggroll/core/error/ErSessionException.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  python/eggroll/core/conf_keys.py
  python/eggroll/core/constants.py
  python/eggroll/core/session.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: bug, enhancement, v2.x

#333 Feature 2.0 rollpair fix gc coredump
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, enhancement, v2.x

#336 Feature 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  python/eggroll/core/client.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/grpc/factory.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: enhancement, v2.x

#338 Optimises thread numbers
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/GrpcUtils.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  python/eggroll/core/session.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
Labels: enhancement, v2.x

#340 roll site bugs
  python/eggroll/roll_site/roll_site.py
Labels: bug, v2.x

#343 Feature 2.1 core
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  jvm/core/main/scala/com/webank/eggroll/core/error/DistributedRuntimeException.scala
  jvm/core/main/scala/com/webank/eggroll/core/error/ErSessionException.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/pom.xml
  jvm/pom.xml
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/Shuffler.scala
  jvm/roll_pair/pom.xml
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  jvm/roll_site/pom.xml
  proto/core/meta.proto
  python/eggroll/core/conf_keys.py
  python/eggroll/core/constants.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/proto/meta_pb2.py
  python/eggroll/core/session.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: enhancement, v2.x

#344 Commit for bryce:
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: bug, v2.x

#345 1. Modifies retry interval from 0.1s * i to 5s * i if push fails.
  python/eggroll/core/pair_store/roll_site_adapter.py
Labels: v2.x

#346 1. Adds status cleanup after successfully get data.
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
Labels: bug, v2.x

#348 Adds many logs, modifies default values and try-catches
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: enhancement, v2.x

#349 Log optimisations.
  python/eggroll/core/command/command_router.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: enhancement, v2.x

#350 Feature 2.0 rollpair fix gc coredump
  python/eggroll/roll_pair/roll_pair.py
Labels: bug

#351 Log optimisations.
  python/eggroll/core/client.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: enhancement, v2.x

#353 Feature 2.0 core
  conf/eggroll.properties
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  python/eggroll/core/conf_keys.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
Labels: bug, enhancement, v2.x

#355 Roll Site update
  jvm/roll_site/main/scala/RollSiteUtil.scala
  python/eggroll/roll_site/roll_site.py
Labels: bug, v2.x
