Repository FederatedAI/eggroll, pull requests merged in 2020-02, with the labels that each got.

#263 Feature 2.0 rollpair
  jvm/core/main/scala/com/webank/eggroll/core/client/ClusterManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/CommandConstants.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  proto/core/meta.proto
  python/arch/api/table/eggroll2/session_impl.py
  python/eggroll/core/client.py
  python/eggroll/core/command/commands.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/proto/meta_pb2.py
  python/eggroll/roll_pair/__init__.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, enhancement, v2.x

#264 Feature 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/StringConstants.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/TransferModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/TransferClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/GrpcUtils.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/Utils.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/event/listener/PipeHandleNotificationEventListener.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/DefaultPipeFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/PipeFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/DataTransferPipedClient.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/PushStreamProcessor.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobidSessionIdMap.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/Pipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/BasePipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/RollPairSinkPipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/ConfFileBasedFdnRouter.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/utils/Timeouts.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  proto/core/transfer.proto
  python/arch/api/table/session.py
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/core/client.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/constants.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/grpc/factory.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/proto/basic_meta_pb2.py
  python/eggroll/core/proto/command_pb2.py
  python/eggroll/core/proto/proxy_pb2.py
  python/eggroll/core/proto/transfer_pb2.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/transfer_model.py
  python/eggroll/core/utils.py
  python/eggroll/roll_paillier_tensor/roll_paillier_tensor.py
  python/eggroll/roll_pair/__init__.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
  python/eggroll/roll_site/test/test_rollsite_adpter.py
  python/eggroll/roll_site/utils/roll_site_utils.py
  python/eggroll/utils/log_utils.py
Labels: bug, enhancement, v2.x

#265 Feature 2.0 rollpair
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_site/roll_site.py
Labels: bug, enhancement, v2.x

#266 set gc open by default
  python/eggroll/roll_pair/roll_pair.py
Labels: bug

#267 Feature 2.0 core
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/test_roll_site.py
  python/fate_flow/driver/task_executor.py
Labels: bug, v2.x

#268 fix add_done_callback bug
  python/eggroll/roll_site/roll_site.py
Labels: bug, v2.x

#269 Feature 2.0 core
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/roll_site/roll_site.py
  python/fate_flow/driver/task_scheduler.py
  python/fate_flow/entity/constant_config.py
Labels: bug, v2.x

#270 fix hash and add file_utils of FATE
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, v2.x

#271 Feature 2.0 core
  jvm/core/main/java/com/webank/eggroll/core/factory/GrpcChannelFactory.java
  jvm/core/main/scala/com/webank/eggroll/core/error/CommandExceptions.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/TransferModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/TransferClient.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_pair/test/scala/com/webank/eggroll/rollpair/io/TestIo.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/event/listener/PipeHandleNotificationEventListener.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/PushStreamProcessor.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/BasePipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/PacketQueuePipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/RollPairSinkPipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/CascadedCaller.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  proto/core/transfer.proto
  python/arch/api/table/eggroll2/table_impl.py
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/core/client.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/proto/transfer_pb2.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/transfer_model.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/__init__.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
  python/eggroll/roll_site/test/test_rollsite.py
  python/eggroll/roll_site/test/test_rollsite_standalone.py
  python/eggroll/roll_site/utils/roll_site_utils.py
Labels: bug, enhancement, v2.x

#272 add tearDown for RollPairStandalone
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: bug

#276 add sort to collect
  python/arch/api/table/eggroll2/table_impl.py
  python/arch/api/table/table.py
Labels: bug

#279 Feature 2.0 roll paillier tensor
  python/eggroll/core/constants.py
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/core/pair_store/queue_adapter.py
  python/eggroll/roll_paillier_tensor/roll_paillier_tensor.py
  python/eggroll/roll_paillier_tensor/rpt_py_engine.py
  python/eggroll/roll_paillier_tensor/test/tesst_assets.py
  python/eggroll/roll_paillier_tensor/test/test_asyn_rpt.py
  python/eggroll/roll_paillier_tensor/test/test_lr.py
  python/eggroll/roll_paillier_tensor/test/test_lr_gust.py
  python/eggroll/roll_paillier_tensor/test/test_lr_host.py
  python/eggroll/roll_paillier_tensor/test/test_roll_paillier_tensor.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_site/conf/transfer_conf.json
  python/eggroll/roll_site/test/test_rollsite_standalone.py
  python/federatedml/secureprotol/fate_paillier.py
  python/federatedml/secureprotol/fixedpoint.py
  python/federatedml/secureprotol/gmpy_math.py
Labels: enhancement, v2.x

#280 Feature 2.0 core
  conf/log4j2.properties
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/Logging.scala
  jvm/core/test/scala/com/webank/eggroll/core/resourcemanager/TestAssets.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/RollPairSinkPipe.java
  python/eggroll/core/conf_keys.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/test/test_session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair_context.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/test/test_roll_site.py
  python/eggroll/roll_site/test/test_rollsite.py
  python/eggroll/utils/log_utils.py
  python/fate_flow/driver/task_executor.py
Labels: bug, enhancement, v2.x

#283 Feature 2.0 core
  python/eggroll/core/aspects.py
  python/eggroll/core/command/command_router.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/test_roll_site.py
  python/eggroll/utils/log_utils.py
Labels: enhancement, v2.x

#285 Feature 2.0 core
  python/eggroll/core/aspects.py
Labels: enhancement, v2.x

#286 Feature 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/ServerNodeCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/Logging.scala
  python/eggroll/core/aspects.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/utils/log_utils.py
  python/eggroll/utils/profile.py
Labels: bug, v2.x

#287 Eggroll 2.0 core
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
Labels: bug, v2.x

#289 add numba jit to hash_code for high performance
  python/eggroll/core/utils.py
Labels: enhancement, v2.x
