Repository FederatedAI/eggroll, pull requests merged in 2020-07, with the labels that each got.

#408 Feature 2.1 rollpair
  python/eggroll/core/conf_keys.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, enhancement, v2.x

#407 fix the bug:"can not kill the bootstrap process in standalone mode"
  python/eggroll/core/session.py
Labels: bug, v2.x

#411 1. Updates default parameters.
  bin/roll_pair/egg_pair_bootstrap.sh
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  python/eggroll/core/conf_keys.py
Labels: configuration, v2.x

#413 add serdes check and support merge subtract_by_key
  python/eggroll/roll_pair/egg_pair.py
Labels: enhancement, v2.x

#416 Feature 2.1 rollpair
  python/eggroll/core/aspects.py
  python/eggroll/core/client.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/datastructure/__init__.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/utils/log_utils.py
Labels: bug, enhancement

#417 Feature 2.2 core
  BUILD_INFO
  bin/roll_pair/egg_pair_bootstrap.sh
  jvm/core/pom.xml
  jvm/pom.xml
  python/eggroll/__init__.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/utils.py
  python/eggroll/utils/log_utils.py
Labels: v2.x

#418 Feature 2.1 rollsite
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/AddrAuthServerInterceptor.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/model/ProxyServerConf.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/ConfFileBasedFdnRouter.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/FdnRouter.java
  python/eggroll/roll_site/test/test_roll_site.py
Labels: v2.x

#419 Minor enhancements
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
Labels: v2.x

#421 Feature 2.2 core
  conf/applicationContext-proxy.xml
  conf/eggroll.properties
  jvm/core/main/java/com/webank/eggroll/core/grpc/observer/BaseCallerResponseStreamObserver.java
  jvm/core/main/java/com/webank/eggroll/core/retry/Retryer.java
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/transfer/GrpcUtils.scala
  jvm/roll_frame/pom.xml
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/Proxy.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/channel/RedirectClientInterceptor.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/event/listener/PipeHandleNotificationEventListener.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/AddrAuthServerInterceptor.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/DefaultPipeFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/DataTransferPipedClient.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/PushStreamProcessor.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ClientPullResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ClientPushResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ClientUnaryCallResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/PushClientResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/RouteServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/InputStreamOutputStreamNoStoragePipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/InputStreamToPacketUnidirectionalPipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/PacketQueuePipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/impl/PacketToOutputStreamUnidirectionalPipe.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/manager/StatsLogger.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/CascadedCaller.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/ConfFileBasedFdnRouter.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/utils/ProxyToStringUtils.java
  jvm/roll_site/main/resources/applicationContext-proxy.xml
  jvm/roll_site/main/scala/RollSiteUtil.scala
Labels: v2.x

#423 Feature 2.1 rollpair
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_site/roll_site.py
Labels: lang=python, lang=scala, module=core, module=rollpair, reason=enhancement

#422 Feature 2.1 rollsite
  conf/applicationContext-proxy.xml
  conf/log4j2.properties
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/Proxy.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ClientUnaryCallResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/model/ProxyServerConf.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/utils/ToAuditString.java
  jvm/roll_site/main/resources/applicationContext-proxy.xml
  jvm/roll_site/main/resources/log4j2.guest.properties
  jvm/roll_site/main/resources/log4j2.properties
  jvm/roll_site/main/resources/proxy.guest.properties
  jvm/roll_site/main/resources/proxy.host.properties
  jvm/roll_site/main/resources/proxy.properties
Labels: lang=java, module=rollsite, version=v2.x

#426 switch namespace and name
  python/eggroll/roll_pair/roll_pair.py
Labels: module=rollpair, reason=enhancement, version=v2.x

#427 switch namespace and name of cleanup
  python/eggroll/roll_pair/roll_pair.py
Labels: lang=python, module=rollpair, version=v2.x

#428 Feature 2.1 rollpair
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
Labels: lang=python, module=rollpair, reason=bug, version=v2.x

#430 Feature 2.2 core
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ClientUnaryCallResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/PushClientResponseStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/roll_pair/egg_pair.py
Labels: module=rollpair, module=rollsite, version=v2.x

#431 1. Removes deprecated codes.
  python/eggroll/roll_paillier_tensor/__init__.py
  python/eggroll/roll_paillier_tensor/roll_paillier_tensor.py
  python/eggroll/roll_paillier_tensor/rpt_py_engine.py
  python/eggroll/roll_paillier_tensor/test/test_assets.py
  python/eggroll/roll_paillier_tensor/test/test_asyn_rpt.py
  python/eggroll/roll_paillier_tensor/test/test_lr.py
  python/eggroll/roll_paillier_tensor/test/test_lr_2sites.py
  python/eggroll/roll_paillier_tensor/test/test_lr_gust.py
  python/eggroll/roll_paillier_tensor/test/test_lr_host.py
  python/eggroll/roll_paillier_tensor/test/test_roll_paillier_tensor.py
Labels: version=v2.x
