Repository FederatedAI/eggroll, pull requests merged in 2020-01, with the labels that each got.

#227 Feature 2.0 core
  bin/eggroll_boot_standalone.sh
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/log4j2.properties
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/test/resources/log4j2.properties
  jvm/roll_pair/test/resources/log4j2-test.properties
  python/eggroll/core/serdes/eggroll_serdes.py
  python/eggroll/core/session.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/test/test_interface.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/utils/log_utils.py
Labels: v2.x

#229 Logger and command / transfer channel error info
  bin/eggroll_boot_standalone.sh
  conf/log4j2.properties
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  python/eggroll/core/client.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/io/kv_adapter.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/serdes/eggroll_serdes.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/utils.py
  python/eggroll/roll_paillier_tensor/roll_paillier_tensor.py
  python/eggroll/roll_pair/__init__.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_interface.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/utils/log_utils.py
Labels: v2.x

#232 Feature 2.0 core
  bin/eggroll_boot_standalone.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  python/eggroll/core/grpc/factory.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/test/test_interface.py
Labels: v2.x

#230 Merge back from master
  .github/ISSUE_TEMPLATE/--issue-report.md
  api/cluster/eggroll.py
  computing/processor.py
  core/pom.xml
Labels: v1.x

#235 Feature 2.0 core
  .gitignore
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  python/eggroll/core/grpc/factory.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_interface.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: v2.x

#236 Feature 2.0 rollpair
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
Labels: bug, v2.x

#237 change count serdes type
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: bug, v2.x

#238 Minor optimizations on static_er_conf, startup script and threadpool size
  bin/roll_pair/egg_pair_bootstrap.sh
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  python/eggroll/core/client.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/session.py
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_pair/test/test_interface.py
  python/eggroll/roll_pair/test/test_performance.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#240 set gc for RollPairContext
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/Proxy.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/PushStreamProcessor.java
  python/eggroll/core/pair_store/__init__.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, enhancement, v2.x

#241 Feature 2.0 core
  python/eggroll/core/transfer/transfer_service.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
Labels: v2.x

#243 Deploy 2.x
  bin/eggroll.sh
  conf/eggroll.properties
  deploy/Eggroll Deployment Guide.md
Labels: v2.x

#244 Feature 2.0 core
  bin/eggroll.sh
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
Labels: v2.x

#246 Feature 2.0 core
  bin/eggroll_boot.sh
  bin/eggroll_boot_standalone.sh
  data/meta_h2/eggroll_meta.h2.mv.db
  doc/api.md
  jvm/core/main/java/com/webank/eggroll/core/client/NodeManagerClient.java
  jvm/core/main/scala/com/webank/eggroll/core/Bootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/client/ClusterManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/event/listener/PipeHandleNotificationEventListener.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/DataTransferPipedClient.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/CascadedCaller.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/ConfFileBasedFdnRouter.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  jvm/roll_site/test/java/com/webank/eggroll/rollsite/piped/TestPipedClient.java
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/core/client.py
  python/eggroll/core/conf_keys.py
  python/eggroll/core/pair_store/roll_site.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: v2.x

#247 bugfix: roll_pair_master classpath config
  conf/eggroll.properties
Labels: v2.x

#248 Feature 2.0 rollpair
  python/arch/api/eggroll.py
  python/arch/api/table/eggroll/__init__.py
  python/arch/api/table/eggroll/session_impl.py
  python/arch/api/table/eggroll/table_impl.py
  python/arch/api/table/eggroll2/table_impl.py
  python/arch/api/table/session.py
  python/arch/api/transfer/cluster.py
  python/arch/api/transfer/standalone.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/session.py
  python/eggroll/core/test/test_pair_store.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, enhancement, v2.x

#250 enhance FATE api
  python/arch/api/table/eggroll2/session_impl.py
  python/arch/api/table/eggroll2/table_impl.py
Labels: enhancement, v2.x

#245 Update eggroll.sh
  bin/eggroll.sh
  conf/eggroll.properties
  deploy/Eggroll Deployment Guide.md
  deploy/deploy.sh
Labels: v2.x

#252 bug fix of database dirty read
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
Labels: bug, v2.x

#253 Session kill one and all, reduce and aggregate, serialization level.
  jvm/core/main/java/com/webank/eggroll/core/client/ClusterManagerClient.java
  jvm/core/main/java/com/webank/eggroll/core/client/NodeManagerClient.java
  jvm/core/main/scala/com/webank/eggroll/core/client/ClusterManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/client/NodeManagerClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/CommandConstants.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/TypesAndStatus.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ClusterManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/NodeManagerBootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/util/JdbcTemplate.scala
  jvm/core/test/scala/com/webank/eggroll/core/clustermanager/TestClusterManagerClient.scala
  jvm/core/test/scala/com/webank/eggroll/core/nodemanager/TestNodeManager.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  python/eggroll/core/client.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/commands.py
  python/eggroll/core/grpc/factory.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/session.py
  python/eggroll/core/test/session_test_asset.py
  python/eggroll/core/test/test_session.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: v2.x

#254 Fixes bugs in session mechanism
  jvm/core/main/scala/com/webank/eggroll/core/ErSession.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  python/eggroll/core/session.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: v2.x

#255 Feature 2.0 rollsite framework
  conf/route_table.json
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/test_rollsite.py
  python/eggroll/roll_site/test/test_rollsite_standalone.py
Labels: v2.x

#258 Roll Site and startup fixes
  bin/eggroll_boot.sh
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/applicationContext-proxy.xml
  conf/eggroll.properties
  conf/log4j2.properties
  conf/route_table.json
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandRouter.scala
  jvm/core/main/scala/com/webank/eggroll/core/error/CommandExceptions.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/metadata/StoreCrudOperator.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/Scheduler.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  python/arch/api/table/eggroll2/table_impl.py
  python/arch/api/transfer/roll_site_bridge.py
  python/eggroll/core/client.py
  python/eggroll/core/command/command_router.py
  python/eggroll/core/pair_store/roll_site.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/roll_pair_test_assets.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
  python/eggroll/roll_site/test/test_rollsite.py
  python/eggroll/roll_site/test/test_rollsite_standalone.py
Labels: v2.x

#259 Minor fixes and removes 'role' in roll site config file.
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandClient.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  python/eggroll/core/command/command_model.py
  python/eggroll/core/command/command_router.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
Labels: v2.x

#262 Logs pid, aggregate enhancements, session enhancements and minor fixes
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/Bootstrap.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/test/scala/com/webank/eggroll/core/clustermanager/TestStoreCrudOperator.scala
  jvm/roll_frame/src/test/scala/com/webank/eggroll/rollframe/RollFrameTests.scala
  jvm/roll_pair/test/scala/com/webank/eggroll/rollpair/io/TestRollPair.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  proto/core/meta.proto
  python/arch/api/table/eggroll2/session_impl.py
  python/eggroll/core/client.py
  python/eggroll/core/command/command_model.py
  python/eggroll/core/error.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/roll_site.py
  python/eggroll/core/proto/meta_pb2.py
  python/eggroll/core/session.py
  python/eggroll/core/utils.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_site/roll_site.py
Labels: v2.x
