Repository FederatedAI/eggroll, pull requests merged in 2020-03, with the labels that each got.

#291 Feature 2.0 core
  conf/eggroll.properties
  conf/route_table.json
  data/meta_h2/eggroll_meta.h2.mv.db
  jvm/core/main/resources/create-eggroll-meta-tables.h2.sql
  jvm/core/main/resources/create-eggroll-meta-tables.sql
  jvm/core/main/scala/com/webank/eggroll/core/command/CommandRouter.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/core/main/scala/com/webank/eggroll/core/constant/StringConstants.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/MetaModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/roll_pair/main/scala/com/webank/eggroll/rollpair/RollPairMasterBootstrap.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  proto/core/meta.proto
  python/eggroll/core/conf_keys.py
  python/eggroll/core/datastructure/broker.py
  python/eggroll/core/meta_model.py
  python/eggroll/core/proto/meta_pb2.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/transfer_pair.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
Labels: enhancement, v2.x

#292 Renames conf of all bootstraps under eggroll.resourcemanager.*
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
Labels: enhancement, v2.x

#294 add mapPartition2 pb python
  api/proto/processor_pb2.py
  api/proto/processor_pb2_grpc.py
Labels: bug, v1.x

#295 V1.x
  api/proto/processor_pb2.py
  api/proto/processor_pb2_grpc.py
Labels: v1.x

#297 Feature 2.0 core
  bin/roll_pair/roll_pair_master_bootstrap.sh
  jvm/core/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  python/eggroll/core/client.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/roll_site_test_asset.py
  python/eggroll/roll_site/test/test_roll_site.py
Labels: bug, enhancement, v2.x

#298 Feature 2.0 rollpair
  jvm/core/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/test/test_pair_store.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: bug, enhancement, v2.x

#299 fix union low performance
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: bug, v2.x

#300 Feature 2.0 fix gc after session stop
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
Labels: bug, v2.x

#302 Feature 2.1 core
  README.md
  bin/eggroll.sh
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  conf/eggroll.properties
  deploy/Eggroll Deployment Guide.md
  deploy/Eggroll部署文档说明.md
  jvm/core/main/scala/com/webank/eggroll/core/meta/NetworkingModel.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/Container.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/ResourceDao.scala
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  jvm/core/main/scala/com/webank/eggroll/core/schedule/TaskPlan.scala
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/client/DataTransferPipedClient.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/observer/ServerPushRequestStreamObserver.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/CascadedCaller.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/service/ConfFileBasedFdnRouter.java
  jvm/roll_site/main/scala/RollSiteUtil.scala
  logo.png
  python/eggroll/core/client.py
  python/eggroll/core/pair_store/adapter.py
  python/eggroll/core/pair_store/lmdb.py
  python/eggroll/core/pair_store/rocksdb.py
  python/eggroll/core/pair_store/roll_site_adapter.py
  python/eggroll/core/session.py
  python/eggroll/core/test/test_pair_store.py
  python/eggroll/roll_pair/egg_pair.py
  python/eggroll/roll_pair/roll_pair.py
  python/eggroll/roll_pair/test/test_roll_pair.py
  python/eggroll/roll_pair/utils/gc_utils.py
  python/eggroll/roll_site/roll_site.py
  python/eggroll/roll_site/test/test_roll_site.py
Labels: v2.x

#303 1 update eggroll.sh and test_roll_site.pypy
  bin/eggroll.sh
Labels: enhancement, v2.x

#304 Bug fixes and minor enhancements
  bin/roll_pair/egg_pair_bootstrap.sh
  bin/roll_pair/roll_pair_master_bootstrap.sh
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/GrpcServerFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/factory/ProxyGrpcStubFactory.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/grpc/service/DataTransferPipedServerImpl.java
  jvm/roll_site/main/java/com/webank/eggroll/rollsite/infra/JobStatus.java
  python/eggroll/core/conf_keys.py
  python/eggroll/core/pair_store/roll_site_adapter.py
Labels: bug, enhancement, v2.x

#305 1. Optimises session close logic.
  jvm/core/main/scala/com/webank/eggroll/core/resourcemanager/SessionManager.scala
  python/eggroll/core/constants.py
  python/eggroll/core/session.py
  python/eggroll/roll_pair/test/test_roll_pair.py
Labels: v2.x
