Repository FederatedAI/eggroll, pull requests merged in 2021-01, with the labels that each got.

#496 Error Messages optimisations
  conf/eggroll.properties
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/EggSiteServicer.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/Polling.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/Push.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/TransferExceptionUtils.scala
  python/eggroll/roll_site/roll_site.py
Labels: module=rollsite, reason=enhancement, version=v2.x

#498 1. Adds iperf3 test suites.
  bin/iperf3-client.sh
  bin/iperf3-server.sh
Labels: module=deployment, version=v2.x

#499 1. Fixes typo.
  bin/iperf3-client.sh
Labels: module=deployment, version=v2.x

#497 add requirements of pystack-debugger and support upgrade
  bin/upgrade_helper.py
  requirements.txt
Labels: module=deployment, version=v2.x

#503 Updates grpc default timeout params.
  conf/eggroll.properties
Labels: module=configuration, version=v2.x

#505 support polling authentication
  conf/log4j2.properties
  jvm/core/main/scala/com/webank/eggroll/core/constant/ConfKeys.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/Polling.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/PollingAuthenticator.scala
  jvm/roll_site/main/scala/com/webank/eggroll/rollsite/Router.scala
Labels: lang=scala, module=rollsite, reason=bug, reason=enhancement, reason=new_feature
